server:
  port: 9091

spring:
  application:
    name: LOTTERY-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lotterydb1?createDatabaseIfNotExist=true
    username: root
    password: root@7072
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
   
     